version: '3.3'

services:
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  sqli:
    image: "sqli:latest"
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: |
      wait-for postgres:5432 -- python run.py
